name: Create Archive
on: push
env:
  ITCH_USERNAME: drowlerd-roberto
  ITCH_GAME_ID: dual-interest
  
jobs:
  build:
    name: game zip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: DualInterestGame.zip
        path: ${{ github.workspace }}/src/main/resources/static/

  deployWebGL:
    needs: build
    name: Upload to Itch.io WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: DualInterestGame.zip
          path: DualInterestGame.zip
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: 8osD3cHHsXM3kiIu4vr8Tcumfm24d9Ip82wW7wfv
          gameData: 'DualInterestGame.zip'
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
  deleteArtifacts:
    needs: deployWebGL
    name: Delete Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: |
          DualInterestGame.zip
