name: Create Archive
on: 
 push
env:
  ITCH_USERNAME: drowlerd-roberto
  ITCH_GAME_ID: dual-interest
  
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: src/main/resources/static
          dest: DualInterestGame.zip
      - uses: actions/upload-artifact@v1
        with:
          name: DualInterestGame.zip
          path: build/DualInterestGame.zip
  deployWebGL:
    needs: zip-files
    name: Upload to Itch.io WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: DualInterestGame.zip
          path: build/DualInterestGame.zip
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: 8osD3cHHsXM3kiIu4vr8Tcumfm24d9Ip82wW7wfv
          gameData: ./build${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
